INSERT INTO actors ( actor_name) VALUES ( 'Michael Fassbender');
INSERT INTO actors ( actor_name) VALUES ( 'Katherine Waterston');
INSERT INTO actors ( actor_name) VALUES ( 'Weaver''s Ellen Ripley');
INSERT INTO actors ( actor_name) VALUES ( 'Tom Everett Scott');
INSERT INTO actors ( actor_name) VALUES ( 'Alicia Silverstone');
INSERT INTO actors ( actor_name) VALUES ( 'Charlie Hunnam');
INSERT INTO actors ( actor_name) VALUES ( 'Djimon Hounsou');
INSERT INTO actors ( actor_name) VALUES ( 'Aidan Gillen');
INSERT INTO actors ( actor_name) VALUES ( 'Jude Law');
INSERT INTO actors ( actor_name) VALUES ( 'Eric Bana');
INSERT INTO actors ( actor_name) VALUES ( 'Kingsley Ben-Adir');
INSERT INTO actors ( actor_name) VALUES ( 'Prabhas');
INSERT INTO actors ( actor_name) VALUES ( 'Rana Daggubati');
INSERT INTO actors ( actor_name) VALUES ( 'Anushka Shetty');
INSERT INTO actors ( actor_name) VALUES ( 'Ramya Krishnan');
INSERT INTO actors ( actor_name) VALUES ( 'Sathyaraj');
INSERT INTO actors ( actor_name) VALUES ( 'Chris Pratt');
INSERT INTO actors ( actor_name) VALUES ( 'Zoe Saldana');
INSERT INTO actors ( actor_name) VALUES ( 'Dave Bautista');
INSERT INTO actors ( actor_name) VALUES ( 'Vin Diesel');
INSERT INTO actors ( actor_name) VALUES ( 'Bradley Cooper');
INSERT INTO actors ( actor_name) VALUES ( 'Michael Rooker');
INSERT INTO actors ( actor_name) VALUES ( 'Karen Gillan');
INSERT INTO actors ( actor_name) VALUES ( 'Bryan Cranston');
INSERT INTO actors ( actor_name) VALUES ( 'Jennifer Garner');
INSERT INTO actors ( actor_name) VALUES ( 'Beverly D''Angelo');