INSERT INTO genres (  genre) VALUES (  'Comedy');
INSERT INTO genres (  genre) VALUES (  'Family');
INSERT INTO genres (  genre) VALUES (  'Drama ');
INSERT INTO genres (  genre) VALUES (  'Fantasy');
INSERT INTO genres (  genre) VALUES (  'Fantasy');
INSERT INTO genres (  genre) VALUES (  'Drama');
INSERT INTO genres (  genre) VALUES (  'Drama');
INSERT INTO genres (  genre) VALUES (  'Fantasy');
INSERT INTO genres (  genre) VALUES (  'Comedy');
INSERT INTO genres (  genre) VALUES (  'Triller');
INSERT INTO genres (  genre) VALUES (  'Horror');
INSERT INTO genres (  genre) VALUES (  'Action');